apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv
  labels:
    type: local

spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/jellyfin"